---
title:  "Ioannis Karakasoglou Breier"
description: "A Sample Portfolio of my Data Science Projects"
theme: jekyll-theme-slate
exclude:
  - Gemfile
  - Gemfile.lock
---



# Build settings
#markdown: kramdown

