---
title:  "Ioannis Karakasoglou Breier"
description: "Public Data Science Projects Portfolio"
theme: jekyll-theme-slate
exclude:
  - Gemfile
  - Gemfile.lock
---



# Build settings
#markdown: kramdown

