---
title:  "Projects"
description: "Ioannis Karakasoglou Breier"
theme: jekyll-theme-slate
thumbnail: './project.png'
exclude:
  - Gemfile
  - Gemfile.lock
---



# Build settings
#markdown: kramdown

