---
title:  "Ioannis Karakasoglou Breier"
description: "A Collection of Personal and Educational Data Science Projects"
theme: jekyll-theme-cayman
share-img: "//docs.microsoft.com/en-us/azure/machine-learning/media/data-science-process-overview/tdsp-lifecycle.png"
bigimg: "//docs.microsoft.com/en-us/azure/machine-learning/media/data-science-process-overview/tdsp-lifecycle.png"
exclude:
  - Gemfile
  - Gemfile.lock
---



# Build settings
#markdown: kramdown

