---
title:  "Ioannis Karakasoglou Breier"
description: "A Portfolio of Sample Data Science Projects"
theme: jekyll-theme-slate
exclude:
  - Gemfile
  - Gemfile.lock
---



# Build settings
#markdown: kramdown

