---
title:  "Ioannis Karakasoglou Breier"
description: "Data Science Projects Sample Portfolio "
theme: jekyll-theme-slate
exclude:
  - Gemfile
  - Gemfile.lock
---



# Build settings
#markdown: kramdown

