---
title:  "Things I Learn"
description: "A Collection of Personal and Educational Data Science Projects"
theme: jekyll-theme-cayman
share-img: "//docs.microsoft.com/en-us/azure/machine-learning/media/data-science-process-overview/tdsp-lifecycle.png"
bigimg: "//docs.microsoft.com/en-us/azure/machine-learning/media/data-science-process-overview/tdsp-lifecycle.png"
avatar: "/favicon.png"
google_analytics: "UA-100574901-1"
navbar-links:
  About Me: "aboutme"
  Stuff I Work On:
    - openSUSE: "https://www.opensuse.org"
    - openQA: "https://openqa.opensuse.org"
exclude:
  - Gemfile
  - Gemfile.lock
---



# Build settings
#markdown: kramdown

