---
title:  "Projects"
description: "Ioannis Karakasoglou Breier"
theme: jekyll-theme-slate
thumbnail: 'fa-area-chart'
exclude:
  - Gemfile
  - Gemfile.lock
---



# Build settings
#markdown: kramdown

