---
title:  "Projects"
description: "Ioannis Karakasoglou Breier"
theme: jekyll-theme-minimal
image: 'https://github.com/jkarakas/Projects/blob/master/projects.png'
exclude:
  - Gemfile
  - Gemfile.lock
---



# Build settings
#markdown: kramdown

